# Schema for the configuration files of the multiversion module.

multiversion.settings:
  type: config_object
  label: 'Multiversion settings'
  mapping:
    author_id:
      type: integer
      label: 'Author ID'
